[package]
name = "rna-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "2"
actix-rt = "2"
actix-web = "3"
env_logger = "0.9.0"
