[package]
name = "rna-world"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-http = "2"
actix-rt = "2"
actix-web = "3"
csv = "1.1"
derive_more = "0.99.2"
env_logger = "0.9.0"
serde = { version = "1", features = ["derive"] }
