version: "3.7"

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rna-world
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
